// User-data backup + restore.
//
// What's in a backup:
//   - User overrides on plugins (favorites, custom category/developer,
//     hidden, custom companion app, multi-category)
//   - Custom registry additions (manually added URL+regex sources)
//   - Custom developer→companion mappings
//   - Custom categories the user defined
//   - Custom scan folders (non-standard plugin folders)
//   - Sidebar / sort / view / column-width preferences, theme, audio
//     volume, tutorial-dismissed flag, community-share consent
//   - Project library + every per-project annotation (tags, notes,
//     bounce overrides, ratings, statuses, key overrides, custom
//     status list)
//
// What's NOT in a backup:
//   - The library scan results (regenerated by re-scanning)
//   - Update check results (re-run by "Check for Updates")
//   - Waveform peak cache (regenerated lazily)
//
// Schema is versioned. v1 maps cleanly to the current cache + project
// store fields; future versions can migrate when fields move around.

const fs = require('node:fs/promises');
const fsSync = require('node:fs');
const path = require('node:path');
const { loadCache, saveCache } = require('./cache.cjs');
const { loadProjectStore, saveProjectStore } = require('./projectStore.cjs');

const BACKUP_VERSION = 1;

// Build a backup object from the live cache + project store.
// Both inputs may be null (fresh install with no data); the helpers
// below default to empty values so the export still works.
function buildBackup(cache, projectStore) {
  const c = cache || {};
  const p = projectStore || {};
  return {
    plugrBackup: true,            // sanity marker so a wrong file is caught fast
    version: BACKUP_VERSION,
    exportedAt: new Date().toISOString(),
    library: {
      // All the user-personalization fields from the main cache.
      userOverrides: c.userOverrides || {},
      userRegistryAdditions: c.userRegistryAdditions || {},
      userDeveloperCompanions: c.userDeveloperCompanions || {},
      userCategories: c.userCategories || {},
      customFolders: c.customFolders || [],
      // UI prefs — small, but they round out "restore my Plugr exactly".
      themePreference: c.themePreference || 'auto',
      categorySort: c.categorySort || 'count',
      developerSort: c.developerSort || 'count',
      formatSort: c.formatSort || 'count',
      columnWidths: c.columnWidths || null,
      compatFilter: c.compatFilter || 'all',
      sidebarSectionOrder: c.sidebarSectionOrder || null,
      sortBy: c.sortBy || null,
      sortDir: c.sortDir || null,
      view: c.view || null,
      appView: c.appView || null,
      audioVolume: typeof c.audioVolume === 'number' ? c.audioVolume : 0.8,
      tutorialDismissed: !!c.tutorialDismissed,
      communityShareConsent: c.communityShareConsent || 'unknown',
    },
    projects: {
      projectLibrary: p.projectLibrary || null,
      projectTags: p.projectTags || {},
      projectNotes: p.projectNotes || {},
      projectBounceOverrides: p.projectBounceOverrides || {},
      projectRatings: p.projectRatings || {},
      projectStatuses: p.projectStatuses || {},
      customStatuses: Array.isArray(p.customStatuses) ? p.customStatuses : null,
      projectKeyOverrides: p.projectKeyOverrides || {},
    },
  };
}

// Parse + validate the raw bytes of a candidate backup file. Returns
// the parsed backup on success, or { error } describing what went
// wrong. We're deliberately strict so the user can't accidentally
// import an unrelated JSON file and wipe their data.
function parseBackup(rawText) {
  let data;
  try { data = JSON.parse(rawText); }
  catch (err) { return { error: `Not valid JSON: ${err.message}` }; }
  if (!data || typeof data !== 'object') {
    return { error: 'Backup file is empty or not an object.' };
  }
  if (data.plugrBackup !== true) {
    return { error: "This doesn't look like a Plugr backup file (missing plugrBackup marker)." };
  }
  if (typeof data.version !== 'number' || data.version < 1) {
    return { error: `Unsupported backup version: ${data.version}` };
  }
  if (data.version > BACKUP_VERSION) {
    return { error: `This backup was made by a newer version of Plugr (v${data.version}). Update Plugr to import it.` };
  }
  // Library + projects sections must be present (even if empty).
  if (!data.library || typeof data.library !== 'object') {
    return { error: 'Backup is missing the "library" section.' };
  }
  if (!data.projects || typeof data.projects !== 'object') {
    return { error: 'Backup is missing the "projects" section.' };
  }
  return { backup: data };
}

// Cheap stats so the renderer can render a "Restore this?" preview
// without scanning the whole backup. Counts the things a user
// recognizes: favorites, custom categories, registry sources, tags,
// projects, etc. Everything is best-effort; failures degrade to 0.
function summarizeBackup(backup) {
  function count(obj) {
    if (!obj || typeof obj !== 'object') return 0;
    return Object.keys(obj).length;
  }
  function countFavorites(overrides) {
    if (!overrides || typeof overrides !== 'object') return 0;
    let n = 0;
    for (const v of Object.values(overrides)) {
      if (v && v.favorite) n++;
    }
    return n;
  }
  function countHidden(overrides) {
    if (!overrides || typeof overrides !== 'object') return 0;
    let n = 0;
    for (const v of Object.values(overrides)) {
      if (v && v.hidden) n++;
    }
    return n;
  }
  const lib = backup.library || {};
  const proj = backup.projects || {};
  const projectLibrary = proj.projectLibrary || {};
  const projects = Array.isArray(projectLibrary.projects) ? projectLibrary.projects : [];
  const folders = Array.isArray(projectLibrary.folders) ? projectLibrary.folders : [];
  return {
    exportedAt: backup.exportedAt || null,
    favorites: countFavorites(lib.userOverrides),
    hidden: countHidden(lib.userOverrides),
    overrides: count(lib.userOverrides),
    registryAdditions: count(lib.userRegistryAdditions),
    customCategories: count(lib.userCategories),
    customFolders: Array.isArray(lib.customFolders) ? lib.customFolders.length : 0,
    customCompanions: count(lib.userDeveloperCompanions),
    theme: lib.themePreference || 'auto',
    projects: projects.length,
    projectFolders: folders.length,
    projectTags: count(proj.projectTags),
    projectNotes: count(proj.projectNotes),
    projectRatings: count(proj.projectRatings),
    projectStatuses: count(proj.projectStatuses),
    projectKeyOverrides: count(proj.projectKeyOverrides),
    customStatuses: Array.isArray(proj.customStatuses) ? proj.customStatuses.length : 0,
  };
}

// Apply a parsed backup to disk. Strategy: REPLACE the live cache +
// project store wholesale. We don't merge — "restore" means restore
// the snapshot, not splice it on top of whatever's there. The cache's
// scan-results fields (library, updates, etc.) are preserved from the
// existing on-disk cache so we don't blow away a fresh scan.
async function applyBackup(backup, userDataDir) {
  const lib = backup.library || {};
  const proj = backup.projects || {};

  // Read the existing cache so we can preserve scan results that
  // aren't part of the backup. If there's no existing cache (fresh
  // install), start from an empty object — the next scan fills it.
  let existingCache;
  try { existingCache = (await loadCache(userDataDir)) || {}; }
  catch { existingCache = {}; }

  const mergedCache = {
    ...existingCache,
    // Personalization — fully replace from backup.
    userOverrides: lib.userOverrides || {},
    userRegistryAdditions: lib.userRegistryAdditions || {},
    userDeveloperCompanions: lib.userDeveloperCompanions || {},
    userCategories: lib.userCategories || {},
    customFolders: Array.isArray(lib.customFolders) ? lib.customFolders : [],
    themePreference: lib.themePreference || 'auto',
    categorySort: lib.categorySort || 'count',
    developerSort: lib.developerSort || 'count',
    formatSort: lib.formatSort || 'count',
    columnWidths: lib.columnWidths || null,
    compatFilter: lib.compatFilter || 'all',
    sidebarSectionOrder: lib.sidebarSectionOrder || null,
    sortBy: lib.sortBy || null,
    sortDir: lib.sortDir || null,
    view: lib.view || null,
    appView: lib.appView || null,
    audioVolume: typeof lib.audioVolume === 'number' ? lib.audioVolume : 0.8,
    tutorialDismissed: !!lib.tutorialDismissed,
    communityShareConsent: lib.communityShareConsent || 'unknown',
    // Scan results — keep what's already there. The user can rescan
    // to get fresh results that match the new machine's installed
    // plugins. (We don't drop them here so an accidental restore on
    // the same machine doesn't force a 60-second rescan.)
  };

  const mergedProjectStore = {
    projectLibrary: proj.projectLibrary || null,
    projectTags: proj.projectTags || {},
    projectNotes: proj.projectNotes || {},
    projectBounceOverrides: proj.projectBounceOverrides || {},
    projectRatings: proj.projectRatings || {},
    projectStatuses: proj.projectStatuses || {},
    customStatuses: Array.isArray(proj.customStatuses) ? proj.customStatuses : null,
    projectKeyOverrides: proj.projectKeyOverrides || {},
  };

  await saveCache(userDataDir, mergedCache);
  await saveProjectStore(userDataDir, mergedProjectStore);
  return { ok: true };
}

// Write the JSON to a file path. We pretty-print to make backups
// diff-friendly if the user ever inspects them in a text editor.
async function writeBackupFile(filePath, backup) {
  const tmp = filePath + '.tmp';
  await fs.writeFile(tmp, JSON.stringify(backup, null, 2), 'utf8');
  await fs.rename(tmp, filePath);
  return { ok: true, path: filePath };
}

async function readBackupFile(filePath) {
  if (!fsSync.existsSync(filePath)) {
    return { error: 'File not found.' };
  }
  let raw;
  try { raw = await fs.readFile(filePath, 'utf8'); }
  catch (err) { return { error: `Couldn't read file: ${err.message}` }; }
  return parseBackup(raw);
}

module.exports = {
  BACKUP_VERSION,
  buildBackup,
  parseBackup,
  summarizeBackup,
  applyBackup,
  writeBackupFile,
  readBackupFile,
};
